stages:
  - install
  - test
  - build
  - deploy

install_dependencies:
  stage: install
  image: node:14
  script:
    - npm install

test:
  stage: test
  image: node:14
  script:
    - npm test

build:
  stage: build
  image: node:14
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - echo "Deploy to your hosting environment"
