variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  CI_REGISTRY: docker.io
  CI_REGISTRY_IMAGE: docker.io/htheva/eduprodigi

stages:
  - build
  - test
  - push
  - deploy

before_script:
  - docker info

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
  only:
    - main

test_image:
  stage: test
  image: node:14
  script:
    - npm install
    - npm test
  only:
    - main

push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - main

deploy_image:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - chmod +x deploy.sh
    - ./deploy.sh
  only:
    - main
